environment:
  nodejs_version: "6.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g npm-install-peers
  - npm-install-peers

test_script:
  - node --version
  - npm --version
  - npm run eslint

build: off
